services:
  dynamodb:
    path: dynamodb

  store:
    path: store
    params:
      productsTableResource: ${dynamodb.ProductsTableResource}
      stocksTableResource: ${dynamodb.StocksTableResource}
      productsTable: ${dynamodb.ProductsTableName}
      stocksTable: ${dynamodb.StocksTableName}

  import-service:
    path: import-service
